substitutions:
  name: bat-signal
  friendly_name: Bat-Signal

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  comment: Bat-Signal Light Controller
  min_version: 2023.11.0
  project:
    name: hobbe.Bat-Signal
    version: "2.2"
  on_boot:
    then:
      - light.turn_on:
          id: batsignal
          brightness: 100%
          red: 100%
          green: 75%
          blue: 30%

esp8266:
  board: d1_mini

logger:
  level: WARN
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false

api:

ota:

wifi:
  ap:
    ssid: "${friendly_name} Hotspot"

captive_portal:

web_server:
  log: false

dashboard_import:
  package_import_url: github://hobbe/esphome-bat-signal/bat-signal.yaml@main
  import_full_config: false

binary_sensor:
  platform: status
  name: "Status"

button:
  - platform: restart
    name: "Reboot"
  - platform: factory_reset
    name: "Factory Reset"
    disabled_by_default: true

light:
  - platform: neopixelbus
    id: batsignal
    type: GRB
    variant: WS2812
    pin: GPIO03
    num_leds: 12
    name: Light
    effects:
      - addressable_color_wipe:
          name: Wipe
          colors:
            - red: 100%
              green: 75%
              blue: 30%
              num_leds: 3
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 3
          add_led_interval: 100ms
      - pulse:
      - addressable_rainbow:
          speed: 25
          width: 12
      - random:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: mdi:ip-network
      disabled_by_default: true
    mac_address:
      name: "MAC"
      icon: mdi:network
      disabled_by_default: true
      filters:
        to_upper:
